name: WSL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wsl:
    runs-on: windows-latest
    steps:
      - name: No name
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
